### PR TITLE
Warn on ACE, GOES, and HRC proxy if no new data for 20 minutes [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by jeanconn**
Just an idea to warn on the web-fetches only if the last successful update is more than N minutes old (where N is hard-coded at 20 minutes here).

### CODE REVIEW

**Comment by jeanconn** [comment]
Not sure about the "lockout" idea.  I don't think a repeated hourly warning would be *too* onerous, but I suppose I could set up a hook to disable alerts in the arcwatch code if needed

**Comment by taldcroft** [comment]
I guess what worries me about not having lockouts is that there might be independent issues that get lost.  I.e. one file goes stale, then 2 hrs later a different one goes stale, but in the meantime I will have stopped opening the mails.  The lockout would apply to each watched file separately.

**Comment by taldcroft** [comment]
BTW I am saying "file" but that could be any watched product.

**Comment by jeanconn** [comment]
On the other side, I'm more likely to miss the single note and fix a
problem is there is a steady stream of email messages.

Maybe instead of per-task disarm files and the accompanying code, it would
make sense to construct subject lines that made this easier for both of
us?  Maybe compress the subject line to include a week id and the list of
tasks/files in error (or codes for them)?  Then if you've seen it, you
could, for example, gmail mute the thread if you are OK with the error​,
but a new thread would start on a new combination of task/files in error.
A new thread would also naturally start the next week (or whatever major
time unit we pick).

**Comment by taldcroft** [comment]
Superceded by https://github.com/sot/jobwatch/pull/9

**Pull request closed without merging**
