### PR TITLE
Keep the timeline working without hrc data

### PR DESCRIPTION
**Pull request by jeanconn**
Keep the timeline working without hrc data

This is a super-simple edit that puts in two dummy points of hrc data if there is nothing in the hrc_shield.h5 file.

The edit also just comments out the parts of task schedule intended to update the hrc proxy data file.

I've run this in a dev ska to show it completes.

### CODE REVIEW

**Comment by taldcroft** [comment]
One thing that just occurred to be would be updating the HTML output to include a red note at the top stating that "HRC proxy data are being stubbed out at this time and should be ignored."

**Comment by jeanconn** [comment]
I put it at the top per your request:

hrc_top_warn

And also stuck some more red text in the GOES area and where the hrc proxy image would be:

hrc_goes_warn

missing_fig

About right?  This is now more pieces that need fixing if we get data back.  I also did more commenting and adding than cutting for now.

**Comment by taldcroft** [comment]
Perfect.  Clear to merge if you are satisfied.

**Comment by taldcroft** [comment]
And you need to put in a realtime software change request to Scott.

**Pull request merged**
