### PR TITLE
Wrap ACE p3 fluence calc and plot in a try/except

### PR DESCRIPTION
**Pull request by jeanconn**
Wrap ACE p3 fluence calc and plot in a try/except .

The try/except with print statement should let make_timeline finish and plot other useful values instead of dying on bad/missing "live" p3 data.
```
File "/proj/sot/ska/share/arc/make_timeline.py", line 412, in main
   args.min_flux_samples, args.max_slope_samples)
File "/proj/sot/ska/share/arc/calc_fluence_dist.py", line 62, in get_fluence_percentiles
    fl10, fl50, fl90 = np.percentile(fluences, [10, 50, 90], axis=0)
...
IndexError: cannot do a non-empty take from an empty axes.
```

### CODE REVIEW

**Comment by taldcroft** [comment]
Looks good to me, assuming it has the desired effect.

**Comment by jeanconn** [comment]
For arc, I wasn't sure what "working dev version" really meant, so I set up a dev ska and started a replan central on the side at http://cxc.cfa.harvard.edu/mta/ASPECT/arc_ace_dev/ that looks basically correct to me.

**Comment by taldcroft** [comment]
Ok, write change request as part of this pr and get approval from Scott.  Then merge and install.

**Comment by jeanconn** [comment]
Approval received from Scott.

**Pull request merged**
