### PR TITLE
HRC proxy model update based on the Sep 2017 GOES-16 observation of a strong flare

### PR DESCRIPTION
**Pull request by malgosias**
Details of modeling: https://github.com/chandra-mta/mtanb/blob/g16-hrc-proxy/g16-hrc-proxy/flare-2017-HRC-shield-proxy-calibration.ipynb

### CODE REVIEW

**Comment by swolk** [comment]
As I discussed with you, this is good as far as it goes,  more test data will be needed as the Sun makes it available, but this is far better than what we have otherwise.

**Comment by jeanconn** [comment]
"Good as far as it GOES"...

**Review by jeanconn — CHANGES_REQUESTED** [review]
If the new computation is based on p5, p6, p7 instead of p5, p7, p9, I think a change is needed in the "check for bad values"
```
hrc_bad = (arr['p5'] < 0) | (arr['p7'] < 0) | (arr['p9'] < 0)
```

**Comment by malgosias** [comment]
Good catch, @jeanconn. Updated the "check for the bad values".

**Review by jeanconn — APPROVED** [review]

**Comment by jeanconn** [comment]
I'm good with the code changes but I should have asked about testing before approving.  What testing has been done?

**Comment by malgosias** [comment]
Since it is a very simple change to the code (only a change in the coefficients/columns read, no change in how the json data are ingested or how the output is saved) I did not perform any specific tests of the replan central code. Similarly, I do not recall performing any specific tests of the HRC formula in the past when we updated the replan central code from the old HRC proxy to the "temporary" new HRC proxy. 

- The new model has been developed and is documented in the following notebook: https://github.com/chandra-mta/mtanb/blob/g16-hrc-proxy/g16-hrc-proxy/flare-2017-HRC-shield-proxy-calibration.ipynb. The new coefficients are summarized in the last cell, ``Mod_567_full`` in the table.
- I confirmed that columns 'p5, 'p6', 'p7' are present in the h5 archive in /proj/sot/ska/data/arc3/hrc_shield.h5

**Review by swolk — APPROVED** [review]

**Comment by jeanconn** [comment]
Sure, with your previous changes to the HRC code, I ran replan central in a full on-the side fashion to integration test before we promoted a new version.  In this case with just this trivial update it would be good to know that the code has at least run successfully and will update a local version of the hrc_shield.h5 file.   Also, did you want to change any of the historical data, or just start the new values of the proxy whenever this code is promoted?  Did you want to keep track in the data file about which version was used?

**Comment by malgosias** [comment]
I don't think we need to keep track in the data file of what proxy formula was used (I added a note on this to the comment in get_hrc.py). Regarding a change the historical proxy data in the h5 file, I could update the proxy value between ~Feb 2020 and now using the new formula but this would have to coincide with the launch of the new version to avoid adding "wrong" proxy entries between the update of the h5 file and installation of the new arc version. Perhaps it would be more efficient to update that year of historical data after the new version is installed, if we decide to update?

I will prepare a notebook demonstrating that the code has run successfully and updated a local version of the hrc_shield.h5 file.

**Comment by jeanconn** [comment]
Sounds good Malgosia.  I'm comfortable to make changes to historical data in the hrc_shield.h5 file if it is useful for you and FD agrees on that as part of the promotion plan.  I think you and HRC are the only consumers of the data and it sounds like nothing depends on maintaining the old values (and they could always be recalculated).

**Comment by jeanconn** [comment]
Thanks @malgosias, that seems reasonable and sufficient to me.

**Pull request merged**
