### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by taldcroft**
Copied from `cxotime`.

### CODE REVIEW

**Comment by taldcroft** [comment]
Fair point, I removed the unit testing section.

The PR template does not explicitly call for full end to end testing, but every PR that gets merged should either have documented functional testing or a release test plan (e.g. a checkbox list) that is a lien on the FSDS ticket. The PR here is the right place for that.

**Comment by jeanconn** [comment]
I liked @javierggt's move to the checklist in a release issue instead of a PR for skare3 and that might be an implementation that would make sense here for arc too but will see how it goes.

**Comment by taldcroft** [comment]
I'm not really understanding the pushback on this simple PR. We've tested most PR's for Replan Central. Given that it is a highly mission critical component of operations, this makes good sense. All this PR is doing is providing a template to nicely document testing (or in rare cases a test plan).

**Comment by jeanconn** [comment]
That's fine.  This isn't pushback, I just thought arc was worth some discussion for the reasons you outlined because it is our only package that goes to FSDS "by itself" and I wasn't sure about the best place to track progress and actually move things forward.  The PR template is fine.

**Review by jeanconn — APPROVED** [review]

**Pull request merged**
