### PR TITLE
Set content timestamps to last updated times

### PR DESCRIPTION
**Pull request by jeanconn**

### CODE REVIEW

**Comment by taldcroft** [comment]
Can we close this?

**Comment by jeanconn** [comment]
I closed the other one ( #21 ).  I actually liked these ideas.  My thought was that we'd soak the hourly checker for a bit and then consider these changes plus one to ignore http warnings in the watch_cron_logs check.

**Comment by taldcroft** [comment]
I actually looked at the code now and it has nothing to do with the title at this point.  I agree this is a useful patch, but would name it "Make filtered local copy of MTA ACE data with accurate timestamp"

**Comment by jeanconn** [comment]
It doesn't just do the ACE data but tries to get the timestamps right for all fetched content, so I went with a title trying to contain that.

**Comment by taldcroft** [comment]
Looks like you need to rebase.

**Comment by jeanconn** [comment]
Repushed.

My bigger concern was that you seemed OK with  55ff99d  but were still on the fence about whether f5614d8 would hurt or help us in actually tracking down problems once they were noticed.

**Comment by taldcroft** [comment]
I think your first instinct to base times on the upstream time was right.  We generally have better visibility into anything going wrong with our tools vs. remote data not updating.  This strategy should also make it quite easy to add last-updated timestamps or "Plot is <this old>" info on the Replan Central page.

**Comment by jeanconn** [comment]
OK.

Regarding the "Plot is" info; we can have that from the updated Ska-Web data whether we choose to use it to sync/utime set the dates of the local files or not.  But yes, I still like the idea of using the remote times for the files in our file checking, mostly because we're not adding content or modifying the plots.

**Comment by taldcroft** [comment]
Are you satisfied that the Ska-Web update is good (and safe) for merge?  You could go ahead with that and then merge this to master.  So far I've kinda been doing the One-PR per FD change request and not merging until after approval, but there is really no reason not to follow the more normal model of collecting changes in master and then cutting a release and installing after approval.

**Comment by jeanconn** [comment]
I'll check everything one more time.  Also maybe worth adding a VERSION file to arc someplace?  I'm pretty sure I have flight installed to my dev ska for my Ska-Web testing but now realize I don't have a handy way to check.

**Comment by taldcroft** [comment]
Yes, a version would be handy.

**Comment by jeanconn** [comment]
Also, I suppose we need to cut Ska-Web 0.03 and have an update for skare to be complete.

**Comment by taldcroft** [comment]
Yeah, I wasn't totally clear but I meant to have a new release of Ska-Web and install to flight.

BTW, lately I've been in the habit of installing skare updates first to /proj/sot/ska/test, both to keep this up to date and to make sure nothing goes horribly wrong.

**Comment by jeanconn** [comment]
Have you been installing to /proj/sot/ska/test before or after updating skare master?

There's now an updated Ska-Web pkg.

**Comment by taldcroft** [comment]
Before.

**Comment by jeanconn** [comment]
OK.  I installed https://github.com/sot/skare/tree/ska_web to /proj/sot/ska/test .  I was under the impression you don't like one commit PRs for skare, so I haven't made one .

**Comment by jeanconn** [comment]
We can close this.  If we want to come back to conditionally updating the ACE rates file we can come back to it.  The rest is OBE.

**Pull request closed without merging**
